# Generated by Django 6.0 on 2025-12-21 05:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lighting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='length',
            field=models.FloatField(blank=True, help_text='Room length in meters', null=True, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('bedroom', 'Bedroom'), ('living_room', 'Living Room'), ('kitchen', 'Kitchen'), ('bathroom', 'Bathroom'), ('office', 'Office'), ('classroom', 'Classroom'), ('conference_room', 'Conference Room'), ('hallway', 'Hallway/Corridor'), ('showroom', 'Showroom/Retail'), ('warehouse', 'Warehouse'), ('laboratory', 'Laboratory'), ('hospital_room', 'Hospital Room'), ('other', 'Other')], default='other', help_text='Type of room for lux calculation', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='width',
            field=models.FloatField(blank=True, help_text='Room width in meters', null=True, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='lightingcatalog',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, help_text='Cost in Indian Rupees (₹)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='room',
            name='area',
            field=models.FloatField(help_text='Area in square meters (0.1 - 10,000 m²)', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(10000.0)]),
        ),
        migrations.AlterField(
            model_name='room',
            name='required_lux',
            field=models.FloatField(blank=True, default=300, help_text='Required illuminance in lux', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
